# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('future_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendee', to='lr_app.User')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requester', to='lr_app.User')),
            ],
        ),
    ]
